# proj info
site_name: 'DERO Wiki'
site_description: 'Wiki for DERO'
site_author: 'Sajo8'
site_url: https://dero.wiki/

# repo
repo_name: 'soja811/dero-docs'
repo_url: 'https://github.com/soja811/dero-docs'

# copyright
copyright: 'Copyright 2018 Sajo8, Sajo811, Soja8, Soja811'

# config
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/fav.png'
  palette:
    primary: 'teal'
  language: 'en'
  direction: 'ltr'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html

# customization
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/deroproject'

# extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  #pymdown extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# directory org
pages:
    - Home:
      - Home: index.md
      - Getting Started: Getting-Started.md
    - FAQ:
      - Frequently Asked Questions: Frequently-Asked-Questions.md
    - Guides:
      - Mining:
        - How to Mine DERO: mining/Mining.md
        - XMR-Stak: mining/XMR-Stak-Guide.md
        - XMR-Stak on Linux: mining/XMR-Stak-Linux-Guide.md
        - XMRig: mining/XMRig-Guide.md
        - Pools: mining/Pools.md
        - Cloud Mining: mining/Cloud-Mining.md
        - Mining with a SBC: mining/Mining-with-SBC.md
      - Wallets:
        - Making a Wallet: wallets/Making-a-Wallet.md
        - GUI Wallet: wallets/Using-the-GUI-Wallet.md
        - CLI Wallet: wallets/Using-the-CLI-Wallet.md
        - Making a Paper Wallet: wallets/Making-a-Paper-Wallet.md
        - Restoring your Wallet: wallets/Restoring-your-Wallet.md
